// Settings map · Group 4 · Payroll & Statutory (APX-D §3, pages 4.1–4.11).
// Sources: M03 (payroll & statutory), M05 (expenses & travel), M11 (benefits & FBP), M13 (contract labour),
// P07 (statutory rules as data, legal floors), P23 (tax regime comparison, group insurance, perks), P05 (payslip template).
// Plain data only. Sample company: Kaveri Foods Pvt Ltd. All registration numbers and partner names are fictional.
import type { SettingsGroupDef, SettingsPageDef } from './settings-types';

const INHERITED = 'Inherited from Kaveri Foods Pvt Ltd';
const SECOND_APPROVER = 'Changes need a second approver. Every change is recorded with before and after values.';

/* ---------------- 4.1 Pay groups & calendars ---------------- */
const payGroups: SettingsPageDef = {
  id: '4.1',
  group: 4,
  title: 'Pay groups & calendars',
  summary:
    'A pay group is one legal entity, one pay frequency and one pay calendar. Set the frequency, the calendar and the input cut-off for each group.',
  owner: ['M03'],
  contributes: ['P08'],
  permission: 'payroll.settings.manage',
  permissionHolder: 'Payroll Manager',
  scopes: ['Company', 'Legal entity', 'Pay group'],
  sections: [
    {
      title: 'Pay groups',
      description: 'Each run covers one pay group and one period. An employee belongs to one pay group at a time.',
      settings: [
        {
          key: 'pay.groups',
          label: 'Pay groups',
          kind: 'list',
          columns: ['Pay group', 'Legal entity', 'Frequency', 'Calendar', 'Employees'],
          rows: [
            ['Staff · Karnataka', 'Kaveri Foods Pvt Ltd', 'Monthly', 'Calendar month', '96'],
            ['Staff · Tamil Nadu', 'Kaveri Foods Pvt Ltd (Tamil Nadu)', 'Monthly', 'Calendar month', '34'],
            ['Hosur plant workers', 'Kaveri Foods Pvt Ltd (Tamil Nadu)', 'Fortnightly', '1–15 and 16–end', '108'],
            ['Seasonal packers', 'Kaveri Foods Pvt Ltd', 'Weekly', 'Monday to Sunday', '10'],
          ],
          addLabel: 'Add pay group',
          synonyms: ['payroll group', 'pay frequency', 'weekly pay', 'fortnightly pay'],
        },
        {
          key: 'pay.default_frequency',
          label: 'Default pay frequency for new groups',
          kind: 'radio',
          value: 'Monthly',
          options: ['Monthly', 'Fortnightly', 'Weekly'],
          helper: 'Weekly and fortnightly groups get their own run screens. PF and ESI are added up into the monthly return.',
          starter: true,
          scope: 'Company',
        },
        {
          key: 'pay.offcycle_types',
          label: 'Off-cycle runs allowed',
          kind: 'multiselect',
          value: ['Full and final', 'Bonus', 'Arrears only', 'Correction'],
          options: ['Full and final', 'Bonus', 'Arrears only', 'Correction'],
          helper: 'Off-cycle runs use the same engine, the same approvals and their own bank file.',
          starter: true,
          scope: 'Company',
          synonyms: ['off cycle', 'F&F run', 'supplementary run'],
        },
      ],
    },
    {
      title: 'Pay calendar',
      settings: [
        {
          key: 'pay.calendar_period',
          label: 'Monthly period',
          kind: 'radio',
          value: 'Calendar month (1st to last day)',
          options: ['Calendar month (1st to last day)', '26th to 25th', '21st to 20th'],
          dated: { validFrom: '2026-04-01' },
          scope: INHERITED,
          synonyms: ['pay period', 'payroll month'],
        },
        {
          key: 'pay.pay_day',
          label: 'Pay day',
          kind: 'radio',
          value: 'Last working day of the month',
          options: ['Last working day of the month', '1st of the following month', 'Fixed day of the following month'],
          helper: 'If the pay day is a holiday, pay goes out on the working day before.',
          dated: { validFrom: '2026-04-01' },
          scope: INHERITED,
          synonyms: ['salary date', 'payday'],
        },
        {
          key: 'pay.latest_pay_day',
          label: 'Latest pay date for monthly groups',
          kind: 'number',
          value: 1,
          unit: 'day of the following month',
          min: 1,
          max: 7,
          helper: 'Used for the due-date strip on the payroll home and the late-payment alert.',
          legal: { value: 7, kind: 'max', statute: 'Code on Wages, 2019 s.17 (monthly wages by the 7th of the next month)' },
          scope: 'Company',
          synonyms: ['wage payment deadline', 'payment of wages'],
        },
        {
          key: 'pay.fnf_deadline',
          label: 'Full and final payment after the last working day',
          kind: 'law',
          value: '2 working days',
          law: 'Code on Wages, 2019 s.17(2) (wages on exit for every exit type)',
          helper: 'The final settlement run is created automatically on the approved last working day.',
          synonyms: ['F&F deadline', 'final settlement'],
        },
      ],
    },
    {
      title: 'Cut-off',
      description: 'Inputs are frozen at the cut-off. Late inputs go to the next run as arrears.',
      settings: [
        { key: 'pay.cutoff_day', label: 'Input cut-off', kind: 'number', value: 22, unit: 'day of the month', min: 1, max: 28, starter: true, dated: { validFrom: '2026-04-01' }, helper: 'Hosur plant workers are paid fortnightly; their cut-off is 2 days before each period ends.', synonyms: ['cut off', 'input freeze', 'payroll lock'] },
        { key: 'pay.cutoff_reminder', label: 'Remind input owners before cut-off', kind: 'number', value: 3, unit: 'days', min: 0, max: 10, starter: true, scope: 'Company' },
      ],
    },
  ],
  lastChange: {
    by: 'Suresh Pillai',
    role: 'Payroll Manager',
    at: '2026-06-18T10:40',
    what: 'Added the fortnightly pay group "Hosur plant workers"',
  },
  related: [
    { label: 'Payroll home', screenId: 'PAY-01' },
    { label: 'Weekly and fortnightly runs', screenId: 'PAY-29' },
    { label: 'Payroll set-up wizard', screenId: 'PAY-16' },
  ],
  note: SECOND_APPROVER,
};

/* ---------------- 4.2 Components & templates ---------------- */
const components: SettingsPageDef = {
  id: '4.2',
  group: 4,
  title: 'Components & templates',
  summary:
    'The component library with its wage flags, and the salary templates that turn an annual CTC into a monthly breakup.',
  owner: ['M03'],
  contributes: ['M11'],
  permission: 'payroll.settings.manage',
  permissionHolder: 'Payroll Manager',
  scopes: ['Company', 'Legal entity', 'Grade'],
  sections: [
    {
      title: 'Component library',
      description: 'PF, ESI, PT, gratuity and bonus wages are worked out from these flags, never from component names.',
      settings: [
        {
          key: 'pay.components',
          label: 'Components',
          kind: 'list',
          columns: ['Component', 'Type', 'Taxable', 'Counts for PF', 'Counts for ESI', 'Counts as wages (Code on Wages)', 'Prorated'],
          rows: [
            ['Basic', 'Earning', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'],
            ['Dearness allowance', 'Earning', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'],
            ['House rent allowance', 'Earning', 'Partly', 'No', 'Yes', 'No (exclusion)', 'Yes'],
            ['Special allowance', 'Earning', 'Yes', 'No', 'Yes', 'No (exclusion)', 'Yes'],
            ['Employer PF', 'Employer contribution', 'No', '—', '—', '—', 'No'],
            ['Shift allowance', 'Earning', 'Yes', 'No', 'Yes', 'No (exclusion)', 'No'],
          ],
          addLabel: 'Add component',
          starter: true,
          synonyms: ['pay heads', 'earnings', 'deductions', 'salary components'],
        },
        {
          key: 'pay.component_editor',
          label: 'Component library editor',
          kind: 'link',
          linkScreenId: 'PAY-14',
          linkLabel: 'Open component library',
          helper: 'Edit flags, payslip names, rounding and accounting heads.',
        },
        {
          key: 'pay.fbp_nps_components',
          label: 'Flexible benefit and employer NPS components',
          kind: 'list',
          readOnlyList: true,
          helper: 'These come from Benefits & FBP and are changed there.',
          columns: ['Component', 'Set in', 'In CTC'],
          rows: [
            ['Flexible benefit basket', 'Benefits & FBP', 'Yes'],
            ['Employer NPS', 'Benefits & FBP', 'Yes'],
            ['Meal card', 'Flexible benefit basket', 'Yes'],
          ],
          contributedBy: 'M11',
          synonyms: ['FBP', 'NPS', 'flexi pay'],
        },
      ],
    },
    {
      title: 'Salary templates',
      settings: [
        {
          key: 'pay.templates',
          label: 'Salary templates',
          kind: 'list',
          columns: ['Template', 'Grades', 'Basic', 'Employer PF / ESI / gratuity', 'Version'],
          rows: [
            ['India standard CTC', 'M1–M4', '40 % of CTC', 'Inside CTC', 'v3'],
            ['Executives', 'E1–E3', '50 % of CTC', 'Inside CTC', 'v2'],
            ['Plant workers', 'W1–W2', 'State minimum wage + DA', 'Outside CTC', 'v4'],
            ['Trainees', 'All', 'Fixed ₹15,000', 'Outside CTC', 'v1'],
          ],
          addLabel: 'Add template',
          starter: true,
          synonyms: ['salary structure', 'CTC template', 'pay structure'],
        },
        {
          key: 'pay.template_builder',
          label: 'Template builder and CTC designer',
          kind: 'link',
          linkScreenId: 'PAY-13',
          linkLabel: 'Open template builder',
          helper: 'Formulas, order and a live test employee. Saving creates a new version; past payslips never change.',
        },
        {
          key: 'pay.employer_contrib_in_ctc',
          label: 'Employer PF, ESI and gratuity',
          kind: 'radio',
          value: 'Inside CTC',
          options: ['Inside CTC', 'Outside CTC (on top)'],
          helper: 'Default for new templates. Each template can set its own.',
          starter: true,
          dated: { validFrom: '2026-04-01' },
          scope: INHERITED,
          synonyms: ['CTC inclusive', 'cost to company'],
        },
        {
          key: 'pay.code_wage_rule',
          label: 'Wages rule: 50 % add-back',
          kind: 'law',
          value: 'Exclusions above 50 % of total pay are added back to wages',
          law: 'Code on Wages, 2019 s.2(y); in force 21 Nov 2025 (P07 YX-STAT-21)',
          helper: 'Templates that produce an add-back for the sample employee are flagged when you save.',
          synonyms: ['50 percent rule', 'wage definition'],
        },
      ],
    },
    {
      title: 'Entry mode',
      settings: [
        {
          key: 'pay.entry_mode',
          label: 'How salary is entered',
          kind: 'radio',
          value: 'CTC first',
          options: ['CTC first', 'Structure first'],
          helper: 'CTC first: enter the annual CTC and the template works out the breakup. Fixed amounts can still be entered per employee.',
          starter: true,
          scope: 'Company',
          synonyms: ['CTC based', 'fixed amounts'],
        },
        { key: 'pay.allow_fixed_override', label: 'Allow fixed-amount entry for single employees', kind: 'toggle', value: true, starter: true, scope: 'Company' },
        {
          key: 'pay.basis_options',
          label: 'Pay basis allowed',
          kind: 'multiselect',
          value: ['Monthly CTC', 'Fixed amounts', 'Daily rate'],
          options: ['Monthly CTC', 'Fixed amounts', 'Hourly rate', 'Daily rate'],
          helper: 'Rate-based pay reads approved hours or days from attendance.',
          scope: 'Company',
          synonyms: ['hourly pay', 'daily wages'],
        },
      ],
    },
  ],
  lastChange: {
    by: 'Suresh Pillai',
    role: 'Payroll Manager',
    at: '2026-08-12T15:20',
    what: 'Published version 4 of the "Plant workers" template with the revised Tamil Nadu DA',
  },
  related: [
    { label: 'Suggest split', screenId: 'PAY-42' },
    { label: 'Compensation tab', screenId: 'PAY-12' },
    { label: 'Policies', screenId: 'PLT-31' },
  ],
  note: SECOND_APPROVER,
};

/* ---------------- 4.3 Payroll policies ---------------- */
const payrollPolicies: SettingsPageDef = {
  id: '4.3',
  group: 4,
  title: 'Payroll policies',
  summary:
    'How pay is prorated, when a change needs a second look, what net pay is protected, how salary holds start and how pay goes out.',
  owner: ['M03'],
  permission: 'payroll.settings.manage',
  permissionHolder: 'Payroll Manager',
  scopes: ['Company', 'Legal entity', 'Pay group'],
  sections: [
    {
      title: 'Calculation',
      settings: [
        {
          key: 'pay.day_basis',
          label: 'Day basis for proration',
          kind: 'radio',
          value: 'Calendar days',
          options: ['Calendar days', '30 days', '26 days'],
          helper: 'Used when a component has no formula of its own. Pay is never prorated twice.',
          starter: true,
          dated: { validFrom: '2026-04-01' },
          overrides: [{ scope: 'Hosur plant workers', value: '26 days', validFrom: '2026-06-01' }],
          synonyms: ['proration', 'LOP days', 'per day salary'],
        },
        {
          key: 'pay.variance_threshold',
          label: 'Flag payslips whose net pay changes by more than',
          kind: 'percent',
          value: 10,
          min: 1,
          max: 50,
          unit: '% change in net pay',
          helper: 'Payslips that change more than this against last period, or gain or lose a component, need an acknowledgement before approval.',
          starter: true,
          scope: 'Company',
          synonyms: ['variance review', 'pay change check'],
        },
        { key: 'pay.unexplained_change_threshold', label: 'Flag net pay changes, when nothing was entered, of more than', kind: 'percent', value: 20, min: 5, max: 100, unit: '%', starter: true, scope: 'Company', synonyms: ['impossible values'] },
      ],
    },
    {
      title: 'Recoveries and protected net',
      settings: [
        {
          key: 'pay.protected_net',
          label: 'Protected net pay',
          kind: 'percent',
          value: 55,
          unit: '% of gross',
          min: 50,
          max: 100,
          helper: 'If loan EMIs, advance instalments or other recoveries would take net pay below this, they are deferred to the next run.',
          legal: { value: 50, kind: 'min', statute: 'Code on Wages, 2019 s.18 (total deductions up to 50 % of wages)' },
          dated: { validFrom: '2026-04-01' },
          scope: INHERITED,
          synonyms: ['minimum take home', 'recovery limit', 'deduction cap'],
        },
        {
          key: 'pay.deduction_cap',
          label: 'Total deductions cap',
          kind: 'law',
          value: '50 % of wages (75 % where co-operative society dues are included)',
          law: 'Code on Wages, 2019 s.18; Payment of Wages Act, 1936 s.7(3) as transitional value',
          helper: 'Court orders come first, then early wage draws, loans, advances and carry-forwards.',
          synonyms: ['garnishment', 'court order'],
        },
      ],
    },
    {
      title: 'One-time pay and holds',
      settings: [
        {
          key: 'pay.one_time_types',
          label: 'One-time pay types',
          kind: 'list',
          columns: ['Type', 'Earning or deduction', 'Taxable', 'Needs approval'],
          rows: [
            ['Festival advance recovery', 'Deduction', '—', 'No'],
            ['Referral bonus', 'Earning', 'Yes', 'Yes'],
            ['Production incentive', 'Earning', 'Yes', 'Yes'],
            ['Notice pay recovery', 'Deduction', '—', 'Yes'],
            ['Arrears', 'Earning', 'Yes', 'No'],
          ],
          addLabel: 'Add one-time pay type',
          starter: true,
          synonyms: ['ad hoc pay', 'bonus', 'incentive', 'arrears'],
        },
        {
          key: 'pay.hold_triggers',
          label: 'Start a salary hold automatically when',
          kind: 'multiselect',
          value: ['Absconding timeline starts', 'Payment failed or returned', 'Exit clearance pending'],
          options: ['Absconding timeline starts', 'Payment failed or returned', 'Exit clearance pending', 'Documents pending after joining'],
          helper: 'While pay is held, PF, ESI and TDS are still computed and deposited on the accrued pay. Only the net is held.',
          starter: true,
          scope: 'Company',
          synonyms: ['salary hold', 'withhold', 'stop salary'],
        },
      ],
    },
    {
      title: 'Payment and statutory choices',
      settings: [
        {
          key: 'pay.cash_cheque_allowed',
          label: 'Allow cash or cheque payment',
          kind: 'toggle',
          value: false,
          helper: 'Bank transfer is the default. When on, each cash or cheque employee needs a reason and approval, and goes to the disbursement register.',
          starter: true,
          scope: 'Company',
          synonyms: ['cash salary', 'cheque payment'],
        },
        {
          key: 'pay.maternity_topup',
          label: 'Top up maternity benefit to full salary',
          kind: 'toggle',
          value: false,
          helper: 'ESIC-covered employees get their benefit from ESIC and no employer line.',
          starter: true,
          dated: { validFrom: '2026-04-01' },
          scope: 'Company',
          synonyms: ['maternity pay'],
        },
        {
          key: 'pay.maternity_weeks',
          label: 'Maternity benefit',
          kind: 'law',
          value: '26 weeks at average daily wage, plus ₹3,500 medical bonus where no pre and post-natal care is given',
          law: 'Maternity Benefit Act, 1961 s.5 and s.8 (Code on Social Security, 2020 ch. VI)',
        },
        {
          key: 'pay.bonus_method',
          label: 'Statutory bonus payment',
          kind: 'radio',
          value: 'Annual, with a monthly provision',
          options: ['Annual, with a monthly provision', 'Monthly, as part of salary'],
          helper: 'Annual bonus is paid after the financial year closes, within the legal deadline.',
          dated: { validFrom: '2026-04-01' },
          overrides: [{ scope: 'Kaveri Foods Pvt Ltd (Tamil Nadu)', value: 'Monthly, as part of salary' }],
          synonyms: ['bonus', 'Payment of Bonus'],
        },
        {
          key: 'pay.bonus_percent',
          label: 'Bonus rate',
          kind: 'percent',
          value: 8.33,
          min: 8.33,
          max: 20,
          unit: '% of bonus wage',
          helper: 'Must stay between 8.33 % and 20 %.',
          legal: { value: 8.33, kind: 'min', statute: 'Payment of Bonus Act, 1965 s.10 and s.11 (Code on Social Security, 2020 ch. XI allows up to 20 %)' },
          dated: { validFrom: '2026-04-01' },
          scope: INHERITED,
          synonyms: ['bonus percentage'],
        },
        {
          key: 'pay.query_assignee',
          label: 'Payslip queries go to',
          kind: 'select',
          value: 'Payroll team queue',
          options: ['Payroll team queue', 'Suresh Pillai', 'Entity payroll admin'],
          helper: 'Employees raise a query from the payslip viewer. Replies stay in the app.',
          scope: 'Company',
          synonyms: ['payslip query', 'salary query'],
        },
        {
          key: 'pay.policies_link',
          label: 'Payroll policy rules',
          kind: 'link',
          linkScreenId: 'PLT-31',
          linkLabel: 'Open payroll policies',
          helper: 'Conditions on any field, including custom fields, are edited in the rule builder.',
        },
      ],
    },
  ],
  lastChange: {
    by: 'Meera Iyer',
    role: 'Finance Manager',
    at: '2026-09-02T11:05',
    what: 'Raised protected net pay from 50 % to 55 % of gross',
  },
  related: [
    { label: 'Salary holds & releases', screenId: 'PAY-06' },
    { label: 'One-time pay', screenId: 'PAY-05' },
    { label: 'Payments & files', screenId: 'PAY-10' },
    { label: 'Payslip query queue', screenId: 'PAY-20' },
    { label: 'Bonus computation', screenId: 'PAY-24' },
  ],
  note: SECOND_APPROVER,
};

/* ---------------- 4.4 Payslip layout ---------------- */
const payslipLayout: SettingsPageDef = {
  id: '4.4',
  group: 4,
  title: 'Payslip layout',
  summary:
    'The payslip layout for each legal entity, with a sample-employee preview. Fields the law requires on a wage slip are locked.',
  owner: ['M03'],
  contributes: ['P05'],
  permission: 'payroll.settings.manage',
  permissionHolder: 'Payroll Manager',
  scopes: ['Legal entity', 'Pay group'],
  sections: [
    {
      title: 'Layouts',
      settings: [
        {
          key: 'payslip.layouts',
          label: 'Layouts per entity',
          kind: 'list',
          columns: ['Legal entity', 'Pay group', 'Layout', 'Languages', 'Version'],
          rows: [
            ['Kaveri Foods Pvt Ltd', 'All', 'Standard with YTD', 'English, Kannada', 'v5'],
            ['Kaveri Foods Pvt Ltd (Tamil Nadu)', 'Staff · Tamil Nadu', 'Standard with YTD', 'English, Tamil', 'v3'],
            ['Kaveri Foods Pvt Ltd (Tamil Nadu)', 'Hosur plant workers', 'Compact with days strip', 'Tamil, English', 'v2'],
          ],
          addLabel: 'Add layout',
          starter: true,
          synonyms: ['payslip format', 'payslip design', 'salary slip'],
        },
        {
          key: 'payslip.editor',
          label: 'Payslip layout editor',
          kind: 'link',
          linkScreenId: 'PAY-15',
          linkLabel: 'Edit payslip layout',
          helper: 'Sections, component order, employer box, YTD and logo, with a preview for a sample employee. A published payslip keeps its layout version.',
        },
        {
          key: 'payslip.mandatory_fields',
          label: 'Mandatory wage-slip fields',
          kind: 'law',
          value: 'Locked on every layout',
          law: 'Code on Wages (Central) Rules, wage slip form',
        },
      ],
    },
    {
      title: 'Content',
      settings: [
        { key: 'payslip.show_employer_box', label: 'Show employer contributions box', kind: 'toggle', value: true, starter: true, scope: INHERITED },
        { key: 'payslip.show_ytd', label: 'Show year-to-date totals', kind: 'toggle', value: true, starter: true, scope: INHERITED, synonyms: ['YTD'] },
        { key: 'payslip.show_leave_balance', label: 'Show leave balances', kind: 'toggle', value: false, starter: true, scope: INHERITED },
      ],
    },
    {
      title: 'PDF protection',
      description: 'Coming soon. Payslip notifications never carry the payslip; they link into the app.',
      settings: [
        {
          key: 'payslip.pdf_password',
          label: 'Password-protect downloaded PDFs',
          kind: 'toggle',
          value: false,
          helper: 'Downloaded payslips open only with the password below.',
          availability: 'Proposed (B19)',
          scope: 'Company',
          synonyms: ['payslip password', 'encrypted payslip'],
        },
        {
          key: 'payslip.pdf_password_format',
          label: 'Password format',
          kind: 'select',
          value: 'First 4 letters of PAN + date of birth (DDMM)',
          options: ['First 4 letters of PAN + date of birth (DDMM)', 'Employee ID + date of birth (DDMMYYYY)', 'Date of birth (DDMMYYYY)'],
          availability: 'Proposed (B19)',
          scope: 'Company',
        },
      ],
    },
  ],
  lastChange: {
    by: 'Suresh Pillai',
    role: 'Payroll Manager',
    at: '2026-07-09T16:30',
    what: 'Published a Tamil-first layout for Hosur plant workers',
  },
  related: [
    { label: 'Payslip viewer', screenId: 'PAY-21' },
    { label: 'Publish payslips', screenId: 'PAY-09' },
  ],
  note: SECOND_APPROVER,
};

/* ---------------- 4.5 Tax ---------------- */
const tax: SettingsPageDef = {
  id: '4.5',
  group: 4,
  title: 'Tax',
  summary:
    'Windows for regime choice, declarations and proofs, and the reminders employees get before each deadline.',
  owner: ['M03'],
  contributes: ['P23'],
  permission: 'payroll.settings.manage',
  permissionHolder: 'Payroll Manager',
  scopes: ['Company', 'Legal entity'],
  sections: [
    {
      title: 'Regime',
      settings: [
        {
          key: 'tax.default_regime',
          label: 'Default tax regime',
          kind: 'law',
          value: 'New regime',
          law: 'Income-tax Act, 2025 (P07 IN.TDS for tax year 2026-27)',
          helper: 'The employee chooses in their tax workspace. After the cut-off only HR can change it, with a reason.',
          synonyms: ['old regime', 'new regime'],
        },
        {
          key: 'tax.regime_cutoff',
          label: 'Regime choice cut-off',
          kind: 'date',
          value: '2026-05-31',
          dated: { validFrom: '2026-04-01' },
          scope: INHERITED,
          synonyms: ['regime lock', 'regime change'],
        },
      ],
    },
    {
      title: 'Declarations and proofs',
      settings: [
        { key: 'tax.declaration_open', label: 'Declaration window opens', kind: 'date', value: '2026-04-01', starter: true, scope: INHERITED, synonyms: ['investment declaration', 'IT declaration'] },
        { key: 'tax.declaration_close', label: 'Declaration window closes', kind: 'date', value: '2026-04-30', starter: true, scope: INHERITED, after: 'tax.declaration_open' },
        { key: 'tax.joiner_declaration_days', label: 'Declaration window for joiners', kind: 'number', value: 30, unit: 'days after joining', min: 7, max: 90, starter: true, scope: 'Company' },
        { key: 'tax.proof_open', label: 'Proof window opens', kind: 'date', value: '2027-01-01', starter: true, scope: INHERITED, after: 'tax.declaration_close', synonyms: ['investment proof', 'POI'] },
        { key: 'tax.proof_close', label: 'Proof window closes', kind: 'date', value: '2027-02-28', starter: true, scope: INHERITED, after: 'tax.proof_open' },
        {
          key: 'tax.after_cutoff',
          label: 'After the proof cut-off',
          kind: 'radio',
          value: 'Drop unproven items and spread extra tax over remaining months',
          options: ['Drop unproven items and spread extra tax over remaining months', 'Drop unproven items and recover extra tax in the next run'],
          helper: 'Only verified proof amounts count after the cut-off.',
          starter: true,
          scope: 'Company',
        },
        {
          key: 'tax.landlord_pan_threshold',
          label: 'Landlord PAN needed when annual rent is above',
          kind: 'law',
          value: '₹1,00,000',
          law: 'Income-tax rules on HRA exemption (P07 IN.TDS)',
          synonyms: ['HRA', 'rent receipt'],
        },
      ],
    },
    {
      title: 'Reminders',
      settings: [
        {
          key: 'tax.reminder_days',
          label: 'Remind employees before each window closes',
          kind: 'multiselect',
          value: ['7 days', '3 days', '1 day'],
          options: ['14 days', '7 days', '3 days', '1 day'],
          starter: true,
          scope: 'Company',
          synonyms: ['tax reminder'],
        },
        {
          key: 'tax.regime_compare',
          label: 'Show "Compare tax regimes" to employees',
          kind: 'toggle',
          value: true,
          helper: 'Old and new regime on the employee’s projected salary. Marked "Estimate, not tax advice". Never shown to managers.',
          contributedBy: 'P23',
          starter: true,
          scope: 'Company',
          synonyms: ['tax planner', 'regime comparison'],
        },
        {
          key: 'tax.regime_compare_reminder',
          label: 'Suggest comparing regimes before the cut-off',
          kind: 'number',
          value: 10,
          unit: 'days before',
          min: 0,
          max: 30,
          contributedBy: 'P23',
          starter: true,
          scope: 'Company',
        },
      ],
    },
  ],
  lastChange: {
    by: 'Suresh Pillai',
    role: 'Payroll Manager',
    at: '2026-09-22T09:45',
    what: 'Set the proof window for tax year 2026-27 to 1 Jan – 28 Feb 2027',
  },
  related: [
    { label: 'Tax workspace', screenId: 'PAY-22' },
    { label: 'Proof verification queue', screenId: 'PAY-23' },
    { label: 'Compare tax regimes', screenId: 'PAY-41' },
  ],
  note: SECOND_APPROVER,
};

/* ---------------- 4.6 Loans & advances ---------------- */
const loans: SettingsPageDef = {
  id: '4.6',
  group: 4,
  title: 'Loans & advances',
  summary:
    'Loan and salary-advance types, who can ask, how much and over how many EMIs, interest, and how pre-closure and EMI pauses work.',
  owner: ['M03'],
  permission: 'payroll.settings.manage',
  permissionHolder: 'Payroll Manager',
  scopes: ['Company', 'Legal entity', 'Grade'],
  sections: [
    {
      title: 'Loan types',
      settings: [
        {
          key: 'loan.types',
          label: 'Loan and advance types',
          kind: 'list',
          columns: ['Type', 'Maximum', 'EMIs', 'Interest', 'Eligible after'],
          rows: [
            ['Salary advance', '1 month’s net pay', 'Up to 3', 'None', '6 months'],
            ['Festival advance', '₹15,000', 'Up to 10', 'None', '6 months'],
            ['Personal loan', '₹1,50,000', 'Up to 24', '6 % a year', '1 year'],
            ['Vehicle loan (M1–M4)', '₹3,00,000', 'Up to 36', '7 % a year', '2 years'],
          ],
          addLabel: 'Add loan type',
          starter: true,
          synonyms: ['salary advance', 'employee loan', 'EMI'],
        },
      ],
    },
    {
      title: 'Limits and eligibility',
      settings: [
        { key: 'loan.max_open', label: 'Open loans per employee', kind: 'number', value: 1, min: 1, max: 5, starter: true, scope: 'Company' },
        {
          key: 'loan.eligibility',
          label: 'Not eligible while',
          kind: 'multiselect',
          value: ['On probation', 'Serving notice', 'Salary on hold'],
          options: ['On probation', 'Serving notice', 'Salary on hold', 'Under disciplinary inquiry'],
          starter: true,
          scope: 'Company',
        },
        {
          key: 'loan.emi_cap',
          label: 'EMI limit',
          kind: 'percent',
          value: 40,
          unit: '% of monthly net pay',
          min: 5,
          max: 50,
          helper: 'Checked when the request is made. Payroll still defers an EMI that would breach protected net pay.',
          legal: { value: 50, kind: 'max', statute: 'Code on Wages, 2019 s.18 (total deductions up to 50 % of wages)' },
          overrides: [{ scope: 'Grades W1–W2', value: 25 }],
          synonyms: ['EMI cap', 'loan recovery'],
        },
      ],
    },
    {
      title: 'Interest',
      settings: [
        { key: 'loan.default_interest', label: 'Default interest rate', kind: 'percent', value: 6, unit: '% a year', min: 0, max: 20, dated: { validFrom: '2026-04-01' }, scope: 'Company', synonyms: ['loan interest'] },
        {
          key: 'loan.perquisite_rule',
          label: 'Perquisite on concessional loans',
          kind: 'law',
          value: 'Benchmark rate on 1 April minus your rate; loans up to ₹20,000 in total are exempt',
          law: 'Income-tax perquisite rules on interest-free or concessional loans (P07 IN.TDS)',
          synonyms: ['loan perquisite'],
        },
      ],
    },
    {
      title: 'Pre-closure and pause',
      settings: [
        { key: 'loan.preclosure', label: 'Allow pre-closure', kind: 'toggle', value: true, starter: true, scope: 'Company' },
        { key: 'loan.preclosure_charge', label: 'Pre-closure charge', kind: 'percent', value: 0, unit: '% of balance', min: 0, max: 5, starter: true, scope: 'Company' },
        { key: 'loan.pause_max', label: 'EMI pauses allowed per loan', kind: 'number', value: 2, unit: 'months', min: 0, max: 6, helper: 'HR pauses with a reason. The schedule moves out by the paused months.', starter: true, scope: 'Company', synonyms: ['EMI holiday', 'skip EMI'] },
        { key: 'loan.exit_recovery', label: 'Balance at exit', kind: 'radio', value: 'Recover in full and final', options: ['Recover in full and final', 'Ask for a repayment plan'], starter: true, scope: 'Company' },
      ],
    },
  ],
  lastChange: {
    by: 'Meera Iyer',
    role: 'Finance Manager',
    at: '2026-07-21T14:10',
    what: 'Added the vehicle loan type for grades M1–M4',
  },
  related: [
    { label: 'Loans & advances', screenId: 'PAY-17' },
    { label: 'Loan request', screenId: 'PAY-18' },
  ],
  note: SECOND_APPROVER,
};

/* ---------------- 4.7 Statutory set-up ---------------- */
const statutory: SettingsPageDef = {
  id: '4.7',
  group: 4,
  title: 'Statutory set-up',
  summary:
    'Registrations for each entity, statute and state, the choices the law leaves to you, how each return is filed, and who signs as deductor. Rates and ceilings are set by law and shown read-only.',
  owner: ['M03'],
  contributes: ['P07'],
  permission: 'payroll.statutory.manage',
  permissionHolder: 'Payroll Manager',
  scopes: ['Legal entity', 'State'],
  sections: [
    {
      title: 'Registrations',
      description: 'Switching a statute on runs a completeness check. Files are not generated until it passes.',
      settings: [
        {
          key: 'stat.registrations',
          label: 'Registrations',
          kind: 'list',
          columns: ['Legal entity', 'Statute', 'State', 'Number', 'Status'],
          rows: [
            ['Kaveri Foods Pvt Ltd', 'EPF', 'Karnataka', 'KNBNG0012345000', 'Complete'],
            ['Kaveri Foods Pvt Ltd', 'ESI', 'Karnataka', '53000123450001001', 'Complete'],
            ['Kaveri Foods Pvt Ltd', 'Professional tax', 'Karnataka', 'PTEC 100245678', 'Complete'],
            ['Kaveri Foods Pvt Ltd (Tamil Nadu)', 'EPF', 'Tamil Nadu', 'TNMAS0067890000', 'Complete'],
            ['Kaveri Foods Pvt Ltd (Tamil Nadu)', 'ESI', 'Tamil Nadu', '51000678900001001', 'Complete'],
            ['Kaveri Foods Pvt Ltd (Tamil Nadu)', 'Labour welfare fund', 'Tamil Nadu', 'Applied, number awaited', 'Due 15 Oct 2026'],
          ],
          addLabel: 'Add registration',
          sensitive: true,
          synonyms: ['PF code', 'ESI code', 'PT registration', 'establishment code'],
        },
        {
          key: 'stat.setup_link',
          label: 'Statutory set-up per entity',
          kind: 'link',
          linkScreenId: 'CMP-02',
          linkLabel: 'Open statutory set-up',
          helper: 'Registrations, legal options, filing mode and deductor details with a completeness check per statute.',
        },
      ],
    },
    {
      title: 'Legal options',
      description: 'Choices the law leaves to the employer. They take effect from the date you set.',
      settings: [
        {
          key: 'stat.pf_wage_basis',
          label: 'PF contribution on',
          kind: 'radio',
          value: 'Wage ceiling (₹15,000)',
          options: ['Wage ceiling (₹15,000)', 'Actual PF wage'],
          dated: { validFrom: '2026-04-01' },
          overrides: [{ scope: 'Kaveri Foods Pvt Ltd (Tamil Nadu)', value: 'Actual PF wage', validFrom: '2026-07-01' }],
          synonyms: ['PF ceiling', 'PF on actual'],
        },
        {
          key: 'stat.pf_employer_share_basis',
          label: 'Employer PF share on',
          kind: 'radio',
          value: 'Same as employee',
          options: ['Same as employee', 'Wage ceiling only'],
          dated: { validFrom: '2026-04-01' },
          scope: INHERITED,
        },
        { key: 'stat.vpf_allowed', label: 'Allow voluntary PF', kind: 'toggle', value: true, scope: 'Company', synonyms: ['VPF'] },
        {
          key: 'stat.gratuity_provision',
          label: 'Gratuity provisioning method',
          kind: 'radio',
          value: 'Monthly formula (15/26 × years)',
          options: ['Monthly formula (15/26 × years)', 'Actuarial valuation'],
          dated: { validFrom: '2026-04-01' },
          scope: INHERITED,
          synonyms: ['gratuity provision'],
        },
        {
          key: 'stat.gratuity_company_cap',
          label: 'Gratuity payable up to',
          kind: 'money',
          value: 2000000,
          helper: 'You may pay more than the legal ceiling, never less.',
          legal: { value: 2000000, kind: 'min', statute: 'Payment of Gratuity Act, 1972 s.4(3) (Code on Social Security, 2020 s.53)' },
          scope: 'Company',
        },
        { key: 'stat.lwf_applicable', label: 'Labour welfare fund applies', kind: 'toggle', value: true, dated: { validFrom: '2026-04-01' }, scope: INHERITED, synonyms: ['LWF'] },
      ],
    },
    {
      title: 'Set by law',
      description: 'Maintained by YukthiX from the published rules. Open the rules browser for history and sources.',
      settings: [
        { key: 'stat.pf_ceiling', label: 'PF wage ceiling', kind: 'law', value: '₹15,000 a month', law: 'EPF & MP Act, 1952; EPF Scheme para 26A (P07 IN.EPF)', synonyms: ['PF ceiling'] },
        { key: 'stat.pf_employee_rate', label: 'Employee PF contribution', kind: 'law', value: '12 % of PF wage', law: 'EPF & MP Act, 1952 s.6 (P07 IN.EPF)' },
        { key: 'stat.esi_ceiling', label: 'ESI eligibility ceiling', kind: 'law', value: '₹21,000 a month (₹25,000 for persons with disability)', law: 'ESI Act, 1948; ESI (Central) Rules (P07 IN.ESI)', synonyms: ['ESI limit'] },
        { key: 'stat.esi_rates', label: 'ESI contribution', kind: 'law', value: 'Employee 0.75 %, employer 3.25 %', law: 'ESI (Central) Rules r.51 (P07 IN.ESI)' },
        { key: 'stat.gratuity_eligibility', label: 'Gratuity eligibility', kind: 'law', value: '5 years (fixed-term: 1 year, pro rata); ceiling ₹20,00,000', law: 'Payment of Gratuity Act, 1972 s.4; Code on Social Security, 2020 s.53' },
        { key: 'stat.pt_ka', label: 'Professional tax · Karnataka', kind: 'law', value: '₹200 a month from ₹25,000 gross; ₹2,500 a year at most', law: 'Karnataka Tax on Professions, Trades, Callings and Employments Act, 1976 (P07 IN.PT.KA)', synonyms: ['PT slab'] },
        { key: 'stat.pt_tn', label: 'Professional tax · Tamil Nadu', kind: 'law', value: 'Half-yearly slabs, up to ₹1,250 each half year', law: 'Tamil Nadu Municipal Laws, profession tax schedule (P07 IN.PT.TN)' },
        { key: 'stat.lwf_ka', label: 'Labour welfare fund · Karnataka', kind: 'law', value: 'Employee ₹50, employer ₹100, yearly in January', law: 'Karnataka Labour Welfare Fund Act, 1965 (P07 IN.LWF.KA)' },
        { key: 'stat.lwf_tn', label: 'Labour welfare fund · Tamil Nadu', kind: 'law', value: 'Employee ₹20, employer ₹40, yearly in January', law: 'Tamil Nadu Labour Welfare Fund Act, 1972 (P07 IN.LWF.TN)' },
        { key: 'stat.rules_browser', label: 'Statutory rules browser', kind: 'link', linkScreenId: 'CMP-08', linkLabel: 'View statutory rules' },
      ],
    },
    {
      title: 'Filing and deductor',
      settings: [
        {
          key: 'stat.filing_mode',
          label: 'Filing mode per statute',
          kind: 'list',
          columns: ['Legal entity', 'Statute', 'Filing mode'],
          rows: [
            ['Kaveri Foods Pvt Ltd', 'TDS (Form 138)', 'YukthiX makes the file, you upload'],
            ['Kaveri Foods Pvt Ltd', 'PF / ESI / PT / LWF', 'Portal-ready files, you upload'],
            ['Kaveri Foods Pvt Ltd (Tamil Nadu)', 'TDS (Form 138)', 'Filing partner'],
            ['Kaveri Foods Pvt Ltd (Tamil Nadu)', 'PF / ESI / PT / LWF', 'Compliance partner'],
          ],
          addLabel: 'Set filing mode',
          synonyms: ['filing partner', 'self file', 'ECR upload'],
        },
        { key: 'stat.tan', label: 'TAN · Kaveri Foods Pvt Ltd', kind: 'text', value: 'BLRK12345E', sensitive: true, scope: 'Kaveri Foods Pvt Ltd', synonyms: ['deductor', 'TAN'] },
        { key: 'stat.responsible_person', label: 'Responsible person for TDS', kind: 'text', value: 'Meera Iyer, Finance Manager', helper: 'Taken into every return. Never retyped per return.', sensitive: true, overrides: [{ scope: 'Kaveri Foods Pvt Ltd (Tamil Nadu)', value: 'Suresh Pillai, Payroll Manager' }] },
      ],
    },
    {
      title: 'Compliance calendar',
      settings: [
        {
          key: 'stat.calendar_reminders',
          label: 'Remind before each statutory due date',
          kind: 'multiselect',
          value: ['7 days', '3 days', 'On the day'],
          options: ['14 days', '7 days', '3 days', '1 day', 'On the day'],
          helper: 'Due dates come from the compliance calendar. You set only when you are reminded.',
          starter: true,
          scope: 'Company',
          synonyms: ['due date', 'ECR due', 'challan due'],
        },
        { key: 'stat.calendar_recipients', label: 'Reminders go to', kind: 'multiselect', value: ['Payroll Manager', 'Finance Manager'], options: ['Payroll Manager', 'Finance Manager', 'HR Business Partner', 'Compliance owner'], scope: 'Company' },
      ],
    },
  ],
  lastChange: {
    by: 'Suresh Pillai',
    role: 'Payroll Manager',
    at: '2026-09-15T12:25',
    what: 'Switched PF for Kaveri Foods Pvt Ltd (Tamil Nadu) to actual PF wage from 1 Jul 2026',
  },
  related: [
    { label: 'Statutory hub', screenId: 'CMP-01' },
    { label: 'Statutory registers', screenId: 'CMP-03' },
    { label: 'Coverage monitor', screenId: 'PAY-30' },
  ],
  note: SECOND_APPROVER + ' Statutory rates are never settings: they come from the statutory rules and are read-only.',
};

/* ---------------- 4.8 Expenses & travel ---------------- */
const expenses: SettingsPageDef = {
  id: '4.8',
  group: 4,
  title: 'Expenses & travel',
  summary:
    'Expense categories, the policy matrix by grade and city tier, limits, mileage and per diem, receipts, GST, over-limit handling, payment route, advances, travel desk and corporate cards.',
  owner: ['M05'],
  permission: 'expense.settings.manage',
  permissionHolder: 'Finance Manager',
  scopes: ['Company', 'Legal entity', 'Grade', 'Category'],
  sections: [
    {
      title: 'Categories and policy',
      settings: [
        {
          key: 'exp.categories',
          label: 'Categories',
          kind: 'list',
          columns: ['Category', 'Accounting head', 'Taxable', 'GST eligible', 'Receipt above'],
          rows: [
            ['Air travel', 'Travel – domestic', 'No', 'Yes', '₹0'],
            ['Hotel stay', 'Travel – lodging', 'No', 'Yes', '₹0'],
            ['Local conveyance', 'Conveyance', 'No', 'No', '₹500'],
            ['Meals', 'Staff welfare', 'No', 'Yes', '₹500'],
            ['Internet and phone', 'Communication', 'No', 'Yes', '₹500'],
            ['Client entertainment', 'Business promotion', 'No', 'Yes', '₹0'],
          ],
          addLabel: 'Add category',
          helper: 'Taxable categories reach payroll as taxable reimbursement. Others don’t affect TDS.',
          starter: true,
          synonyms: ['expense heads', 'claim types', 'perquisite', 'taxable reimbursement'],
        },
        {
          key: 'exp.policy_matrix',
          label: 'Policy matrix (category × grade × city tier)',
          kind: 'list',
          columns: ['Category', 'Grade', 'Tier 1', 'Tier 2', 'Tier 3'],
          rows: [
            ['Hotel stay (per night)', 'W1–W2, G1–G3', '₹3,000', '₹2,500', '₹2,000'],
            ['Hotel stay (per night)', 'M1–M2', '₹4,500', '₹3,500', '₹2,500'],
            ['Hotel stay (per night)', 'M3–M4', '₹6,000', '₹4,500', '₹3,000'],
            ['Hotel stay (per night)', 'E1–E3', '₹9,000', '₹7,000', '₹5,000'],
            ['Meals (per day)', 'All', '₹1,200', '₹900', '₹700'],
          ],
          addLabel: 'Add policy row',
          dated: { validFrom: '2026-04-01' },
          starter: true,
          synonyms: ['expense policy', 'entitlement', 'eligibility matrix'],
        },
        { key: 'exp.policy_matrix_editor', label: 'Expense policy matrix editor', kind: 'link', linkScreenId: 'EXP-07', linkLabel: 'Open policy matrix' },
        {
          key: 'exp.limits',
          label: 'Other limits',
          kind: 'list',
          columns: ['Category', 'Per line', 'Per day', 'Per trip', 'Per month'],
          rows: [
            ['Local conveyance', '₹1,500', '₹2,000', '—', '₹6,000'],
            ['Internet and phone', '—', '—', '—', '₹1,000'],
            ['Client entertainment', '₹5,000', '—', '₹15,000', '₹20,000'],
          ],
          addLabel: 'Add limit',
          dated: { validFrom: '2026-04-01' },
          starter: true,
          synonyms: ['expense limit', 'cap'],
        },
        {
          key: 'exp.city_tiers',
          label: 'City tiers',
          kind: 'list',
          columns: ['Tier', 'Cities'],
          rows: [
            ['Tier 1', 'Bengaluru, Chennai, Mumbai, Delhi NCR, Hyderabad, Kolkata, Pune'],
            ['Tier 2', 'Mysuru, Coimbatore, Madurai, Hubballi, Kochi'],
            ['Tier 3', 'All other cities and towns, including Hosur'],
          ],
          addLabel: 'Add tier',
          starter: true,
          synonyms: ['city class', 'metro'],
        },
      ],
    },
    {
      title: 'Mileage and per diem',
      settings: [
        {
          key: 'exp.mileage_rates',
          label: 'Mileage rates',
          kind: 'list',
          columns: ['Vehicle', 'Rate per km', 'Monthly km cap'],
          rows: [
            ['Two-wheeler', '₹4', '1,200'],
            ['Car', '₹12', '1,500'],
            ['Electric car', '₹9', '1,500'],
          ],
          addLabel: 'Add vehicle type',
          dated: { validFrom: '2026-04-01' },
          starter: true,
          synonyms: ['mileage', 'per km', 'fuel'],
        },
        {
          key: 'exp.per_diem',
          label: 'Per diem',
          kind: 'list',
          columns: ['Where', 'Grade', 'Rate per day'],
          rows: [
            ['Tier 1 city', 'All', '₹1,200'],
            ['Tier 2 and 3 city', 'All', '₹800'],
            ['Singapore', 'E1–E3', 'SGD 90'],
            ['United Arab Emirates', 'E1–E3', 'AED 250'],
          ],
          addLabel: 'Add per diem rate',
          dated: { validFrom: '2026-04-01' },
          starter: true,
          synonyms: ['per diem', 'daily allowance', 'DA travel'],
        },
      ],
    },
    {
      title: 'Receipts, OCR and GST',
      settings: [
        { key: 'exp.receipt_threshold', label: 'Receipt needed above', kind: 'money', value: 500, helper: 'Below this, the employee self-declares. Each category can set its own.', starter: true, scope: 'Company', synonyms: ['bill mandatory', 'self declaration'] },
        { key: 'exp.ocr', label: 'Read receipts automatically (OCR)', kind: 'toggle', value: true, helper: 'OCR only fills fields in. It never approves. Uses AI credits.', starter: true, scope: 'Company', synonyms: ['scan receipt'] },
        { key: 'exp.gst_capture', label: 'Capture GST details for input credit', kind: 'toggle', value: true, helper: 'On GST-eligible lines: supplier GSTIN, invoice number and date, taxable value and tax split.', scope: 'Company', synonyms: ['GST', 'input tax credit', 'GSTIN'] },
        { key: 'exp.fx_tolerance', label: 'Flag employee-entered exchange rates differing by more than', kind: 'percent', value: 3, unit: '%', min: 0, max: 20, starter: true, scope: 'Company', synonyms: ['forex', 'currency'] },
      ],
    },
    {
      title: 'Over-limit and payment',
      settings: [
        {
          key: 'exp.over_limit',
          label: 'Claims above the limit',
          kind: 'radio',
          value: 'Allow with justification and an extra approval',
          options: ['Allow with justification and an extra approval', 'Hard block'],
          helper: 'Each category can switch to hard block. Amounts are never cut silently.',
          starter: true,
          overrides: [{ scope: 'Client entertainment', value: 'Hard block' }],
          synonyms: ['over limit', 'exceed policy'],
        },
        { key: 'exp.extra_approver', label: 'Extra approver for the excess', kind: 'select', value: 'Department head', options: ['Department head', 'Finance Manager', 'Entity head', 'Reporting manager’s manager'], starter: true, scope: 'Company' },
        {
          key: 'exp.payment_route',
          label: 'Pay approved claims',
          kind: 'radio',
          value: 'In the next payroll',
          options: ['In the next payroll', 'By direct payout'],
          helper: 'Finance can still send a single claim by direct payout.',
          starter: true,
          scope: 'Company',
          synonyms: ['reimbursement route'],
        },
        { key: 'exp.direct_payout_above', label: 'Always pay by direct payout above', kind: 'money', value: 50000, scope: 'Company' },
      ],
    },
    {
      title: 'Advances, travel and cards',
      settings: [
        { key: 'exp.advance_settle_days', label: 'Settle trip advances within', kind: 'number', value: 30, unit: 'days after the trip ends', min: 7, max: 90, starter: true, scope: 'Company', synonyms: ['advance settlement', 'imprest'] },
        {
          key: 'exp.advance_recovery_instalments',
          label: 'Recover unsettled advances in up to',
          kind: 'number',
          value: 3,
          unit: 'instalments',
          min: 1,
          max: 12,
          helper: 'Each instalment is a payroll deduction within protected net pay.',
          starter: true,
          scope: 'Company',
        },
        { key: 'exp.travel_desk', label: 'Travel desk books tickets and hotels', kind: 'toggle', value: true, helper: 'Company-paid bookings count against the trip budget but are not reimbursed.', scope: 'Company', synonyms: ['travel desk', 'booking'] },
        { key: 'exp.travel_desk_members', label: 'Travel desk members', kind: 'multiselect', value: ['Lakshmi Venkatesan'], options: ['Lakshmi Venkatesan', 'Meera Iyer', 'Arjun Kulkarni'], scope: 'Company' },
        { key: 'exp.corporate_cards', label: 'Import corporate card statements', kind: 'toggle', value: false, helper: 'Match card lines to receipts; employees explain unmatched lines.', availability: 'Wave 6', scope: 'Company', synonyms: ['corporate card', 'card statement'] },
      ],
    },
  ],
  lastChange: {
    by: 'Meera Iyer',
    role: 'Finance Manager',
    at: '2026-08-28T17:05',
    what: 'Raised the Tier 1 hotel limit for grades E1–E3 from ₹8,000 to ₹9,000',
  },
  related: [
    { label: 'Expenses home', screenId: 'EXP-01' },
    { label: 'Advances', screenId: 'EXP-05' },
    { label: 'Card statement import', screenId: 'EXP-08' },
  ],
  note: 'Changes to limits and the policy matrix are dated and need a second approver.',
};

/* ---------------- 4.9 Contract labour ---------------- */
const contractLabour: SettingsPageDef = {
  id: '4.9',
  group: 4,
  title: 'Contract labour',
  summary:
    'Principal-employer registrations, contractor licence checks, the monthly proofs you ask vendors for, the proof cut-off and when contractor bills are held.',
  owner: ['M13'],
  contributes: ['P07'],
  permission: 'clra.settings.manage',
  permissionHolder: 'HR Business Partner',
  scopes: ['Legal entity', 'Location'],
  sections: [
    {
      title: 'Registrations',
      settings: [
        {
          key: 'clra.registrations',
          label: 'Principal-employer registrations',
          kind: 'list',
          columns: ['Establishment', 'Registration', 'Max contract workers', 'Valid to'],
          rows: [
            ['Hosur plant', 'OSH/TN/HSR/2026/00417', '250', '31 Mar 2031'],
            ['Chennai office', 'OSH/TN/CHN/2026/01182', '40', '31 Mar 2031'],
            ['Bengaluru head office', 'Not required (below threshold)', '—', '—'],
          ],
          addLabel: 'Add registration',
          synonyms: ['CLRA registration', 'RC', 'principal employer'],
        },
        { key: 'clra.threshold', label: 'Registration needed from', kind: 'law', value: '50 contract workers (20 for dates before 21 Nov 2025)', law: 'OSH Code, 2020 contract-labour chapter; Contract Labour Act, 1970 s.1(4) for earlier dates' },
      ],
    },
    {
      title: 'Contractor licences',
      settings: [
        { key: 'clra.licence_check', label: 'Block deployment without a valid licence covering the site', kind: 'law', value: 'Always on', law: 'OSH Code, 2020 contract-labour chapter (P07 IN.CLRA)' },
        { key: 'clra.licence_alerts', label: 'Licence and registration expiry alerts', kind: 'multiselect', value: ['60 days', '30 days', '7 days'], options: ['90 days', '60 days', '30 days', '15 days', '7 days'], starter: true, scope: 'Company', synonyms: ['licence expiry', 'renewal'] },
        { key: 'clra.min_age', label: 'Minimum age to deploy', kind: 'law', value: '18 years', law: 'Child and Adolescent Labour Act, 1986; OSH Code, 2020' },
      ],
    },
    {
      title: 'Monthly compliance',
      settings: [
        {
          key: 'clra.checklist',
          label: 'Vendor compliance checklist',
          kind: 'list',
          columns: ['Proof', 'Required at', 'Checked automatically'],
          rows: [
            ['PF ECR and challan', 'All establishments', 'Period, code, workers covered'],
            ['ESI challan', 'All establishments', 'Period, code, amount'],
            ['Wage register', 'All establishments', 'Minimum wage, days paid'],
            ['Wage payment proof', 'All establishments', 'Payment date'],
            ['Attendance muster', 'Hosur plant', 'Days on site'],
          ],
          addLabel: 'Add proof',
          starter: true,
          synonyms: ['vendor compliance', 'challan check'],
        },
        {
          key: 'clra.doc_cutoff',
          label: 'Proofs due by',
          kind: 'number',
          value: 15,
          unit: 'day of the following month',
          min: 1,
          max: 25,
          helper: 'Never later than the statutory due dates.',
          starter: true,
          scope: 'Company',
          synonyms: ['document cut-off'],
        },
        {
          key: 'clra.payment_hold',
          label: 'Contractor bill while proofs are overdue or disputed',
          kind: 'radio',
          value: 'Hold, compliance owner can release with a reason',
          options: ['Hold, compliance owner can release with a reason', 'Alert only'],
          helper: 'Liability alerts fire whatever you choose, because the principal employer is liable for unpaid wages and dues.',
          starter: true,
          scope: 'Company',
          synonyms: ['liability hold', 'vendor payment hold'],
        },
      ],
    },
  ],
  lastChange: {
    by: 'Lakshmi Venkatesan',
    role: 'HR Business Partner',
    at: '2026-08-05T10:15',
    what: 'Added "Attendance muster" to the Hosur plant checklist',
  },
  related: [
    { label: 'Contractors register', screenId: 'CLB-01' },
    { label: 'Vendor compliance tracker', screenId: 'CLB-03' },
    { label: 'Registers & returns', screenId: 'CLB-04' },
  ],
  note: 'Thresholds and licence rules come from the statutory rules and are read-only. Every change is recorded.',
};

/* ---------------- 4.10 Earned wage access ---------------- */
const ewa: SettingsPageDef = {
  id: '4.10',
  group: 4,
  title: 'Earned wage access',
  summary:
    'Let employees draw part of the pay they have already earned this period. The draw is recovered in the next payroll.',
  owner: ['M03'],
  permission: 'payroll.settings.manage',
  permissionHolder: 'Payroll Manager',
  scopes: ['Company', 'Legal entity', 'Pay group'],
  sections: [
    {
      title: 'Availability',
      settings: [
        { key: 'ewa.enabled', label: 'Turn on earned wage access', kind: 'toggle', value: false, starter: true, availability: 'Wave 5', overrides: [{ scope: 'Hosur plant workers', value: true, validFrom: '2026-10-01' }], synonyms: ['EWA', 'salary on demand', 'early pay'] },
        { key: 'ewa.eligibility', label: 'Not available while', kind: 'multiselect', value: ['On probation', 'Serving notice', 'Salary on hold'], options: ['On probation', 'Serving notice', 'Salary on hold', 'Loan EMI deferred'], starter: true, scope: 'Company' },
      ],
    },
    {
      title: 'Limits',
      settings: [
        { key: 'ewa.percent', label: 'Available share of earned-to-date', kind: 'percent', value: 50, unit: '%', min: 10, max: 80, starter: true, dated: { validFrom: '2026-10-01' }, scope: 'Company' },
        { key: 'ewa.min_draw', label: 'Smallest draw', kind: 'money', value: 500, starter: true, scope: 'Company', atMost: 'ewa.max_draw' },
        { key: 'ewa.max_draw', label: 'Largest draw', kind: 'money', value: 10000, starter: true, scope: 'Company' },
        { key: 'ewa.draws_per_period', label: 'Draws per pay period', kind: 'number', value: 3, min: 1, max: 5, starter: true, scope: 'Company', synonyms: ['draws per month'] },
        { key: 'ewa.blackout_days', label: 'No draws in the last days before cut-off', kind: 'number', value: 3, unit: 'days', min: 0, max: 7, starter: true, scope: 'Company' },
      ],
    },
    {
      title: 'Partner and fees',
      settings: [
        { key: 'ewa.funding', label: 'Funding', kind: 'radio', value: 'Partner-funded', options: ['Partner-funded', 'Employer-funded (salary advance)'], helper: 'With partner funding you carry no credit risk.', starter: true, scope: 'Company' },
        { key: 'ewa.partner', label: 'EWA partner connection', kind: 'select', value: 'Pragati Wage Access (sample partner)', options: ['Pragati Wage Access (sample partner)', 'Not connected'], helper: 'A partner service. The fee is shown in rupees before the employee confirms.', scope: 'Company' },
        { key: 'ewa.fee_bearer', label: 'Who pays the fee', kind: 'radio', value: 'Employee', options: ['Employee', 'Employer', 'Split equally'], starter: true, scope: 'Company', synonyms: ['EWA fee'] },
        {
          key: 'ewa.recovery_order',
          label: 'Recovery order',
          kind: 'law',
          value: 'After statutory deductions and court orders, before loans and advances',
          law: 'YukthiX rule: a draw is recovered in full in the next regular payroll, inside the total deductions cap',
        },
        { key: 'ewa.admin_link', label: 'EWA draws and recoveries', kind: 'link', linkScreenId: 'PAY-27', linkLabel: 'Open EWA admin' },
      ],
    },
  ],
  lastChange: {
    by: 'Meera Iyer',
    role: 'Finance Manager',
    at: '2026-09-26T15:40',
    what: 'Turned on earned wage access for Hosur plant workers from 1 Oct 2026',
  },
  related: [
    { label: 'Get paid early (employee)', screenId: 'PAY-26' },
    { label: 'Loans & advances', screenId: 'PAY-17' },
  ],
  note: SECOND_APPROVER,
};

/* ---------------- 4.11 Benefits & FBP ---------------- */
const benefits: SettingsPageDef = {
  id: '4.11',
  group: 4,
  title: 'Benefits & FBP',
  summary:
    'Group insurance plans and dependants, enrolment and endorsement rules, the flexible benefit basket, employer NPS, and the partner-run insurance and perks marketplaces.',
  owner: ['M11'],
  contributes: ['P23', 'P07'],
  permission: 'benefits.settings.manage',
  permissionHolder: 'HR Business Partner',
  scopes: ['Company', 'Legal entity', 'Grade'],
  sections: [
    {
      title: 'Insurance plans',
      settings: [
        {
          key: 'ben.plans',
          label: 'Insurance plans',
          kind: 'list',
          columns: ['Plan', 'Type', 'Cover', 'Insurer', 'Premium share'],
          rows: [
            ['Group health', 'GMC', '₹3,00,000 family floater', 'Nilgiri Insurance Co.', 'Employer 100 %'],
            ['Group health top-up', 'GMC top-up', '₹5,00,000', 'Nilgiri Insurance Co.', 'Employee 100 %'],
            ['Parents cover', 'Parental', '₹2,00,000', 'Nilgiri Insurance Co.', 'Employee 100 %'],
            ['Accident cover', 'GPA', '3 × annual CTC', 'Deccan General Insurance', 'Employer 100 %'],
            ['Life cover', 'GTL', '2 × annual CTC', 'Deccan Life Assurance', 'Employer 100 %'],
          ],
          addLabel: 'Add plan',
          starter: true,
          dated: { validFrom: '2026-04-01' },
          synonyms: ['GMC', 'mediclaim', 'group insurance', 'GTL'],
        },
        {
          key: 'ben.dependants',
          label: 'Dependants covered',
          kind: 'multiselect',
          value: ['Spouse', 'Children (up to 2)', 'Parents or parents-in-law'],
          options: ['Spouse', 'Children (up to 2)', 'Children (any number)', 'Parents or parents-in-law', 'Parents and parents-in-law'],
          helper: 'Parents are on the separate parents cover.',
          starter: true,
          scope: 'Company',
          synonyms: ['family cover', 'dependants'],
        },
        { key: 'ben.child_age_limit', label: 'Children covered up to age', kind: 'number', value: 25, unit: 'years', min: 18, max: 26, starter: true, scope: 'Company' },
      ],
    },
    {
      title: 'Enrolment and endorsements',
      settings: [
        { key: 'ben.open_enrolment_from', label: 'Next open enrolment opens', kind: 'date', value: '2027-03-01', starter: true, helper: 'Repeats every year on the same dates.', scope: 'Company', synonyms: ['enrolment window', 'open enrolment'] },
        { key: 'ben.open_enrolment_to', label: 'Next open enrolment closes', kind: 'date', value: '2027-03-20', starter: true, scope: 'Company', after: 'ben.open_enrolment_from' },
        { key: 'ben.joiner_window', label: 'Joiners enrol within', kind: 'number', value: 30, unit: 'days of joining', min: 7, max: 90, starter: true, scope: 'Company' },
        { key: 'ben.life_event_window', label: 'Life events reported within', kind: 'number', value: 30, unit: 'days of the event', min: 7, max: 90, helper: 'Marriage, birth or adoption, a dependant’s death, divorce.', starter: true, scope: 'Company', synonyms: ['life event', 'add spouse', 'newborn'] },
        { key: 'ben.exit_grace', label: 'Cover continues after the last working day for', kind: 'number', value: 0, unit: 'days', min: 0, max: 60, starter: true, scope: 'Company' },
        { key: 'ben.endorsement_mode', label: 'Send endorsements to the insurer', kind: 'radio', value: 'Monthly file export', options: ['Monthly file export', 'Weekly file export', 'Through a connected broker (add-on)'], starter: true, scope: 'Company', synonyms: ['endorsement', 'add member'] },
        { key: 'ben.prorata_premium', label: 'Charge mid-year additions', kind: 'radio', value: 'Pro rata by days', options: ['Pro rata by days', 'Pro rata by months', 'Full year'], starter: true, scope: 'Company' },
      ],
    },
    {
      title: 'Flexible benefit plan (FBP)',
      settings: [
        {
          key: 'ben.fbp_heads',
          label: 'Flexible benefit basket',
          kind: 'list',
          columns: ['Head', 'Yearly limit', 'Paid', 'Exempt under'],
          rows: [
            ['Meal card', '₹26,400', 'Monthly', 'Old regime only'],
            ['Fuel and vehicle', '₹39,600', 'On claim with bills', 'Old regime only'],
            ['Telephone and internet', '₹18,000', 'On claim with bills', 'Old regime only'],
            ['Leave travel', '₹40,000', 'On claim with bills', 'Old regime only'],
            ['Books and periodicals', '₹12,000', 'On claim with bills', 'Old regime only'],
          ],
          addLabel: 'Add FBP head',
          starter: true,
          dated: { validFrom: '2026-04-01' },
          synonyms: ['FBP', 'flexi basket', 'flexible pay'],
        },
        { key: 'ben.fbp_basket_limit', label: 'Largest flexible benefit basket', kind: 'percent', value: 20, unit: '% of CTC', min: 0, max: 40, starter: true, overrides: [{ scope: 'Grades W1–W2', value: 0 }] },
        { key: 'ben.fbp_window_from', label: 'Allocation window opens', kind: 'date', value: '2026-04-01', starter: true, scope: 'Company', synonyms: ['FBP declaration'] },
        { key: 'ben.fbp_window_to', label: 'Allocation window closes', kind: 'date', value: '2026-04-30', starter: true, scope: 'Company', after: 'ben.fbp_window_from', helper: 'Joiners get 30 days from joining.' },
        { key: 'ben.fbp_bill_window', label: 'Bills accepted until', kind: 'date', value: '2027-02-28', starter: true, dated: { validFrom: '2026-04-01' }, scope: 'Company', after: 'ben.fbp_window_to', synonyms: ['FBP bills'] },
        { key: 'ben.fbp_sweep', label: 'Unclaimed balance at year end or exit', kind: 'radio', value: 'Pay as taxable salary in March', options: ['Pay as taxable salary in March', 'Pay as taxable salary in the last run of the year'], helper: 'Also applies at exit, through full and final.', starter: true, scope: 'Company', synonyms: ['year end sweep', 'taxable balance'] },
      ],
    },
    {
      title: 'Employer NPS',
      settings: [
        { key: 'ben.nps_enabled', label: 'Offer employer NPS', kind: 'toggle', value: true, scope: 'Company', synonyms: ['NPS', '80CCD(2)'] },
        { key: 'ben.nps_percent', label: 'Employer contribution', kind: 'percent', value: 10, unit: '% of basic + DA', min: 0, max: 14, helper: 'Anything above the regime limit is taxable to the employee.', dated: { validFrom: '2026-04-01' }, scope: 'Company' },
        { key: 'ben.nps_employee_choice', label: 'Employees choose to opt in', kind: 'toggle', value: true, scope: 'Company' },
        { key: 'ben.nps_limit', label: 'Employer NPS tax limit', kind: 'law', value: '14 % of basic + DA (new regime), 10 % (old regime)', law: 'Income-tax Act, 2025, employer NPS deduction (80CCD(2) equivalent) (P07 IN.TDS)' },
      ],
    },
    {
      title: 'Marketplaces',
      description: 'Run by partners. YukthiX never advises on or sells insurance.',
      settings: [
        { key: 'ben.insurance_marketplace', label: 'Show group insurance quotes from a licensed partner', kind: 'toggle', value: false, helper: 'Only for companies at or above the insurer’s minimum headcount. The partner receives census fields only.', contributedBy: 'P23', availability: 'Wave 5', scope: 'Company', synonyms: ['buy insurance', 'group health quote'] },
        { key: 'ben.insurance_partner', label: 'Insurance partner', kind: 'select', value: 'Suraksha Insurance Brokers (sample, licensed broker)', options: ['Suraksha Insurance Brokers (sample, licensed broker)', 'Not chosen'], helper: 'Offers are hidden when the partner’s licence has expired.', contributedBy: 'P23', availability: 'Wave 5', scope: 'Company' },
        { key: 'ben.perks_enabled', label: 'Turn on employee perks', kind: 'toggle', value: false, helper: 'Partner offers in the employee app. Never shown on payroll, payslip, tax or statutory screens.', starter: true, contributedBy: 'P23', availability: 'Wave 5', scope: 'Company', synonyms: ['perks', 'discounts'] },
        { key: 'ben.perks_categories', label: 'Perk categories', kind: 'multiselect', value: ['Groceries', 'Learning'], options: ['Phones and electronics', 'Travel', 'Groceries', 'Learning', 'Health and fitness'], contributedBy: 'P23', availability: 'Wave 5', scope: 'Company' },
        { key: 'ben.group_health_link', label: 'Group health marketplace', kind: 'link', linkScreenId: 'PAY-43', linkLabel: 'Open group health' },
      ],
    },
  ],
  lastChange: {
    by: 'Lakshmi Venkatesan',
    role: 'HR Business Partner',
    at: '2026-09-10T11:50',
    what: 'Added the ₹5,00,000 group health top-up for plan year 2026-27',
  },
  related: [
    { label: 'Perks (employee app)', screenId: 'ENG-12' },
    { label: 'Components & templates', screenId: 'PAY-14' },
  ],
  note: SECOND_APPROVER + ' Health and dependant details are private and never shown to managers.',
};

export const GROUP_4: SettingsGroupDef = {
  id: 4,
  title: 'Payroll & Statutory',
  summary:
    'Pay groups, components and templates, payroll policies, payslip layout, tax windows, loans, statutory set-up, expenses, contract labour, earned wage access and benefits.',
  pages: [payGroups, components, payrollPolicies, payslipLayout, tax, loans, statutory, expenses, contractLabour, ewa, benefits],
};
